### ISSUE TITLE
Possible bug with response.headers.Valueof

### ISSUE THREAD

**Issue by martinqvistgard** [quangson91/intellij_rest_cli#3]
First off, huge thanks for implementing a cli runner for http test files! This will be so useful! :100: 

I have started to experiment a bit and i think I ran into a problem with response.headers.valueOf.

I have written a test .http file like this:
```js
POST http://127.0.0.1:81/en/api/auth/login
Content-Type: application/json;charset=UTF-8
Accept: application/json
Cookie: XDEBUG_SESSION=docker

{"username":"xxxx","password":"qwerty"}

> {%
client.test("That request was successful", function() {
    client.assert(response.status === 200, "Response status is not 200");
});

client.test("That Authorization token was returned", function() {
    client.assert(response.headers.valueOf('Authorization') != null);
});

client.test("That there is a value for the auth token", function() {
    client.assert(false, 'token is ' + response.headers.valueOf('Authorization'));
});

%}
```

This is my output from Php Storm (a bit truncated)
![image](https://user-images.githubusercontent.com/703595/89187342-718eff00-d59d-11ea-906a-787c9b4908dc.png)

However, when I run the same script i get the following output:
```
>>> Test script >>>
✓ That request was successful
✓ That Authorization token was returned
✗ That there is a value for the auth token
token is [object Object]
<<< Test script <<<
```

**Comment by quangson91** [comment]
@martinqvistgard Firstly, thank you for the feedback.
You are right. There is a problem with `valueOf` implementation.
I will fix it today :) 
The fixed version will be available soon.

Thank you!

**Comment by quangson91** [comment]
@martinqvistgard I released a new version here: https://github.com/quangson91/intellij_rest_cli/releases/tag/v1.1
This problem is fixed. Please take a look if you have time.

Also, there is a new feature that you can custom generate the test-report (like junit).
So in the CI, we can show the test report.

You can take a look at this repository for more detail: https://github.com/quangson91/demo_intellij_rest_cli/blob/master/.circleci/config.yml#L21

Here is the screenshot of this feature.

<img width="1014" alt="Screen Shot 2020-08-04 at 12 45 50 AM" src="https://user-images.githubusercontent.com/6185205/89212489-b93d7700-d5ed-11ea-87c1-bb729347ef40.png">

Note: you need to add an option "-r test_report_name" if you want to generate the test report. (if the `-r` argument doesn't exist -> there is no test report generated).

Thank you so much for trying this tool 🙇

**Comment by martinqvistgard** [comment]
Thank you! Works like a charm now :)
I stumbled into another problem when testing this out that has to do with variable replacement via {{var}} and i just filed an issue for it.

I will experiment with the reports and using them in gitlab. I will write up a short howto when / if I get it to work.

Many thanks,
/martin

**Comment by quangson91** [comment]
@martinqvistgard Thank you.
So I will close this issue. For the issue related to variable replacement via {{var}} => I will fix it soon.

Thanks!

**Comment by quangson91** [comment]
@all-contributors please add @martinqvistgard for userTesting
